# -*- coding: utf-8 -*-
"""17/2 sáng T6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oy0175VEcTNTeLfUslQDSfhbvAx4GTym
"""

#load library
import pandas as pd
#create dataframe
dataframe = pd.DataFrame()
#add colums
dataframe['Name']=['Lemon','Apple','Banana']
dataframe['Price']=[5,8,7]
dataframe['License']=[False,True,True]
#showdata
dataframe

df= dataframe
df.info()

list(df.columns)
['Name','Price','License']

df.describe()

#loc iloc
df.loc[(df.Price==5)]

df.loc[(df.Price==5)|(df.Name == 'Banana')]

df.loc[(df.Price==5)|(df.Name == 'Banana'),('Name','Price')]

df.iloc[2]
type(df.iloc[2])

df.iloc[[2]]

df.iloc[0:2]

df.iloc[0:2,0:-1]
df.iloc[0:2,-1]

sum = df.Price.sum()
print(sum)

max = df.Price.max()
print(max)

count = df.Price.count()
print(count)

# load library
import pandas as pd
# create url
url = 'http://winterolympicsmedals.com/medals.csv'
# load data
dataframe = pd.read_csv(url)
# show data
dataframe.head()

data = dataframe
data.shape

data.describe()
# std: phuong sai
# mean: gia tri trung binh

data.iloc[0:10] # ~[:10]

data.iloc[[200,]]

data = data.set_index(data['NOC'])
data.loc['GER']

data.loc['USA']

data[data['NOC']=='CAN'].head(10)

data[(data['Year']>=1990)&(data['Year']<=2006) & (data['NOC']=='USA')&(data['Event gender']=='W')&(data['Medal']=='Gold')].head(10)

data['NOC'].value_counts()

data.count()

data['NOC'].count()

data['NOC'].unique()

data.drop('NOC', axis=1).head(10)

data.drop(data.columns[2:4], axis=1).head(10)

data[data['NOC']!='CAN'].head(10)

data = pd.read_csv(url)
data.groupby('NOC').head(10)

data.groupby('NOC').count()

data.groupby(['Year','NOC']).head()

data.groupby(['Year','NOC']).count()

data = pd.read_csv(url)

# apply a function
def uppercase(x):
  return x.upper()
data['Event'].apply(uppercase)[0:2311]

data